### ISSUE TITLE
Issues from the old repo

### ISSUE THREAD

**Issue by Zren** [Zren/plasma-applet-volumewin7mixer#1]
* [x] [Changing the volume with the mousewheel while hovering over applet does not work anymore](https://github.com/Zren/plasma-applet-volumewin7mixer/issues/123)
* [ ] [Chrome/Firefox tab titles in stream name](https://github.com/Zren/plasma-applet-volumewin7mixer/issues/73)
* [x] [Suppress incorrect MPRIS SetPosition calls on loading new media](https://github.com/Zren/plasma-applet-volumewin7mixer/issues/69)
* [ ] [Set as default code will cause apps to start on wrong device instead of current default](https://github.com/Zren/plasma-applet-volumewin7mixer/issues/64)
* [ ] [no icon on KDE 5.8.4](https://github.com/Zren/plasma-applet-volumewin7mixer/issues/51)
* [x] [Optionally turn off the OSD](https://github.com/Zren/plasma-applet-volumewin7mixer/issues/48)
* [ ] [Toggle microphone loopback to speaker](https://github.com/Zren/plasma-applet-volumewin7mixer/issues/38)
* [x] [Audio Volume Settings context menu item is redundant](https://github.com/Zren/plasma-applet-volumewin7mixer/issues/37)
* [ ] [Use theme icons for non-app mixer elements, based on Port](https://github.com/Zren/plasma-applet-volumewin7mixer/issues/36)
* [x] [current track progress is inaccurate](https://github.com/Zren/plasma-applet-volumewin7mixer/issues/35)
* [x] [include current song information in hover-tooltip](https://github.com/Zren/plasma-applet-volumewin7mixer/issues/34)
* [x] [use description instead of name for mixer item labels](https://github.com/Zren/plasma-applet-volumewin7mixer/issues/33)
* [x] [Enable systray?](https://github.com/Zren/plasma-applet-volumewin7mixer/issues/29)
* [x] [Doesn't resizeable the popup window](https://github.com/Zren/plasma-applet-volumewin7mixer/issues/21)
